### ISSUE TITLE
Permission error in the events admin API

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#2147]
### Describe the bug
Non-superusers cannot use the events admin api (for example `/api/v2/admin/events/<pk>/registrations/`), even when they should be allowed to.

### How to reproduce
Steps to reproduce the behaviour:
1. Sign in as not a superuser, but as organiser of an event.
2. Try out the event admin api from the OpenAPI page.
3. Get 403.

### Expected behaviour
It should be allowed.

### Additional context
Thus problem occurs in the OpenAPI tool, so also when actually authenticated in django, not just when using a token.

**Comment by se-bastiaan** [comment]
@DeD1rk Is this not just a 404 in the schema? The one that I fixed in #2146.

The [check for organisers](https://github.com/svthalia/concrexit/blob/master/website/events/api/v2/admin/views.py#L71) is used on more pages. In other words, if you get a 403 on registrations then `/api/v2/admin/events/<pk>/` should not work either I think.

**Comment by se-bastiaan** [comment]
Hmm did some quick debugging, the `is_organiser` check is properly called for that page in the permission class.

**Comment by ColonelPhantom** [comment]
It also seems like the first permission class (IsOrganiser) should return True. (the function `is_organiser` returns True, but I still get 403 for some reason). Honestly, I don't really know what's going on here.

**Comment by DeD1rk** [comment]
I investigated it a bit more:

The problematic views subclass the custom AdminXXXAPIViews in [`website/thaliawebsite/api/v2/admin/views.py`](https://github.com/svthalia/concrexit/blob/c539dff019133dd3175a8cbe1d16f8e2b420aeab/website/thaliawebsite/api/v2/admin/views.py), which have this mixin:

```
class AdminPermissionsMixin:
    def get_permissions(self):
        self.permission_classes.append(IsAdminUser)
        # self.permission_classes.append(DjangoAdminModelPermissions)
        return super().get_permissions()
```

That is, they require `is_staff` (makes sense), but also `DjangoAdminModelPermissions`. Now I'm not quite familiar with Django permissions, but I think the idea is that committee permissions are forwarded to members only through the IsOrganiser permission class, so committee members don't have the required DjangoAdminModelPermissions themselves.

If I'm not mistaken, simply not using the DjangoAdminModelPermissions (not using the AdminXXXAPIViews in the entire events admin API should work just fine (it solves this problem, but I'm not confident that it will not allow non-organisers to do bad things). However, I think having these custom base classes is quite confusing. In the sales app, DjangoAdminModelPermissions (for some reason not `IsAdminUser`) is added manually on each view, which I would say is a more readable approach. In any case, I think we should make sure to be consistent about this kind of things. I'm not sure whether it's better to get rid of AdminXXXApiViews alltogether or just for the event admin, but if we keep them they should at least be documented.

@se-bastiaan @JobDoesburg what do you guys think about this.

**Comment by JobDoesburg** [comment]
@DeD1rk I just verified the problem you're suggesting and that doesn't seem to be the problem. DjangoAdminModelPermissions checks whether the user has permissions. This works by checking for individual permissions, and for group permissions of committees the user is in at that point in time... 
For now, I really cannot reproduce this bug

**Comment by JobDoesburg** [comment]
Turned out to be a misconfiguration on production (and a misunderstanding by Dirk on which permissions were required)
